35 logout with gov
DFE-Digital/early-years-foundation-reform pull request #64
Opened 2021-02-23 14:33 UTC by marcrice12

### Context
https://dfedigital.atlassian.net/jira/software/projects/HFEYP/boards/83?selectedIssue=HFEYP-36
1. need a logout button for all admin pages
2. need a 30 min inactivity session timeout

### Changes proposed in this pull request

### Guidance to review

2021-02-23 15:06 UTC, tonyto approved these changes

2021-02-23 16:37 UTC, guy-roberts approved these changes

2021-02-24 09:17 UTC, guy-roberts reviewed
I changed the devise config to 
```
config.timeout_in = 1.minutes

then waited a couple of minutes

I could still edit and save pages

When it does work, will it clear the current view and go back to the login prompt or will it wait until another request is made ?

2021-02-24 10:12 UTC, guy-roberts requested changes
The user model is not :timeoutable,  so the time out will not happen

2021-02-24 12:02 UTC, guy-roberts approved these changes

2021-02-24 17:31 UTC, tonyto commented on spec/features/admin_home_page_spec.rb
> +RSpec.feature "Admin Homepage", type: :feature do
Is it worth asserting for the `current_user` for these specs?

2021-02-25 12:23 UTC, merged