ER-1187 Aria landmark update
DFE-Digital/early-years-foundation-reform pull request #804
Opened 2024-06-06 09:42 UTC by martikat

[ER-1187](https://dfedigital.atlassian.net.mcas.ms/browse/ER-1187)

2024-06-18 07:53 UTC, martikat commented on app/views/layouts/hero.html.slim
> +      = yield :shared_ctas
I have compared this to what we had before these changes and visually it looks the same. There has been some reorganising here to ensure the `aside` is in the correct place

2024-06-19 09:20 UTC, peterdavidhamilton requested changes

2024-06-19 09:20 UTC, peterdavidhamilton commented on app/views/pages/index.html.slim
> +- content_for(:shared_ctas) do
The naming is confusing. It is the content for the `aside` which  contains...

2024-06-19 09:20 UTC, peterdavidhamilton commented on app/views/pages/index.html.slim
> +- content_for(:shared_ctas) do
And we'd agreed the content blocks would be defined first

2024-06-20 15:22 UTC, peterdavidhamilton commented
I think my previous comment still stands. How are you able to yield other resources?

2024-06-21 13:08 UTC, peterdavidhamilton approved these changes
Yeah, this looks more logical @martikat 👍🏼

2024-06-21 13:12 UTC, merged