Thumbnail update
DFE-Digital/early-years-foundation-reform pull request #834
Opened 2024-07-19 09:29 UTC by martikat

Update to ensure default image is loaded when it has not been set

2024-07-19 10:50 UTC, peterdavidhamilton requested changes
Please implement my suggested refactor and try adding a spec

2024-07-22 13:27 UTC, peterdavidhamilton requested changes

2024-07-22 13:27 UTC, peterdavidhamilton commented on app/helpers/content_helper.rb
> +  # @return [OpenStruct]
`@param`

2024-07-22 13:27 UTC, peterdavidhamilton commented on app/helpers/content_helper.rb
> +  def card_thumbnail(card)
`@param` which might make you decide to rename the variable

2024-07-22 13:27 UTC, peterdavidhamilton commented on app/helpers/content_helper.rb
>    def null_resource(name)
We discussed naming consistency of `placeholder_<Object>`, i.e. `placeholder_resource` and `placeholder_asset` or similar.

2024-07-22 13:27 UTC, peterdavidhamilton commented on spec/helpers/content_helper_spec.rb
> +    let(:null_resource) { helper.null_resource('example') }
This is a very confusing spec. Does it give us greater confidence in our code doing the right thing?

2024-07-22 13:27 UTC, peterdavidhamilton commented on spec/models/page_spec.rb
> +    context 'when help page with image' do
`'when page has image'` or `'with linked asset'`
vs.
`'when page has no image'` or `'without linked asset'`

The first makes for grammatically correct spec docs but the latter is even better.
1. context
2. with or without
3. what specifically

2024-07-29 12:39 UTC, peterdavidhamilton commented on spec/helpers/content_helper_spec.rb
> +        expect(helper.card_thumbnail(page)).to include 'images.ctfassets'
It'd be good if the asset url specs test similarly, ie a FQDN and protocol

2024-07-29 12:39 UTC, peterdavidhamilton commented on spec/helpers/content_helper_spec.rb
> +        expect(helper.card_thumbnail(page)).to include 'https://placehold.co'
`start_with`

2024-07-29 12:39 UTC, peterdavidhamilton commented on app/models/page.rb
> +    return nil if fields[:image].blank?
You could remove `nil` if you like and it'd behave the same because it is implicit

2024-08-05 08:56 UTC, David-Feetenby approved these changes

2024-08-05 09:02 UTC, merged